### ISSUE TITLE
Push Notifiation warning when submitting to Apple

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [DigitalStrawberry/ANE-Share#10]
Hi,

I'm getting this warning when submitting to Apple, since I added your ANE

> TMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement.

I've tried adding the aps-environment entitlement for production, but that just changes the warning, because our app doesnt use Push Notifications, and hence our App certificate does not include the Push Notification stuff.

Do you know how I can stop this warning without totally enabling Push Notifications by generating a new App certificate etc etc ??

**Comment by marpies** [comment]
Hi,

The ANE includes a framework that provides methods for handling notifications (among other helper methods). I'm guessing Apple detects this and assumes that "your app appears to register for push notifications", even though no actual calls are made to connect with APNS. The framework makes the ANE development much easier by not having to write a lot of boilerplate code when dealing with data conversion between AIR and native environment and duplicating the same code across multiple ANEs.

Since you are not using notifications you shouldn't include the aps-environment entitlement, and simply ignore the warning as it shouldn't affect your app submission.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'll let you know if Apple reject the App, but we won't be submitting for a few months as there are a load of other changes we need to do first
