### ISSUE TITLE
How to set title for sharing?

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Share#3]
I couldn't figure out how to set the title for the shared content on wechat app. Is it app specific? like I have to find the right variable name for the SharedData? Many thanks.

**Comment by marpies** [comment]
You can't really affect details like that, since the ANE uses generic sharing method provided by the system and it is up to the selected app how it processes the shared data. You'd probably need to use the [WeChat mobile SDK](http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/mobile/share/android) to achieve what you want.

**Comment by jimmymjing** [comment]
Thanks for answering my question. I'm sorry that I probably didn't make my question clear. I see other sharing ane also allows sharing a text title, like AirNativeShare.instance.showShare(["http://xxx.com", "Hello xxxx", bitmapData]);   but I don't know how to do this by using our ane. thanks in advance.

**Comment by marpies** [comment]
Your example code would translate to this in our ANE:

```as3
var sharedItems:Vector.<SharedData> = new <SharedData>[];
sharedItems.push(new SharedData("http://xxx.com"));
sharedItems.push(new SharedData("Hello xxxx"));
sharedItems.push(new SharedData(bitmapData));
Share.instance.share(sharedItems);
```
